- implemented sound effects
DG-Apps-Studio/words-game pull request #9
Opened 2023-08-01 08:22 UTC by Ehtisham-gillani

2023-08-01 08:35 UTC, Abdulmanan475 requested changes

2023-08-02 06:00 UTC, Ehtisham-gillani commented on app/src/main/java/com/example/testinglib/HomeScreen.kt
Because at this stage we are working on initial build and we will work to implement Navigation Component in next build.

2023-08-02 06:01 UTC, Ehtisham-gillani commented on app/src/main/java/com/example/testinglib/LevelSelection.kt
Ok

2023-08-02 06:04 UTC, Ehtisham-gillani commented on app/src/main/java/com/example/testinglib/MainActivity.kt
When I will work on Navigation Component then I'll do this.

2023-08-02 06:45 UTC, Abdulmanan475 approved these changes

2023-08-02 06:45 UTC, merged